export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const REMOVE_EMPLOYEES = 'REMOVE_EMPLOYEES';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const GET_SELECTED_EMPLOYEES_ID = 'GET_SELECTED_EMPLOYEES_ID';